# -*- coding: utf-8 -*-
"""at_s1_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t9Ywx1pK8hNBgiSIpM90r2nO1lGPCflV
"""

# Commented out IPython magic to ensure Python compatibility.
# # code based on https://gofilipa.github.io/664/analyzing/generating/fine-tune.html
# # First, on the toolbar, where it says RAM DISK, change the hardware accelator to GPU.
# # download following libraries
# %%capture
# %pip install transformers trl

from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    pipeline
)

# load model from containing folder

# if using Google Colab run the following lines
from google.colab import drive
drive.mount('/content/drive')

model = AutoModelForCausalLM.from_pretrained("/content/drive/MyDrive/adventuretime/at_s1_model")
tokenizer = AutoTokenizer.from_pretrained("/content/drive/MyDrive/adventuretime/at_s1_model")

# create a pipe() function that calls our new model
pipe = pipeline('text-generation', model=model, tokenizer=tokenizer, max_length=50)

# text inside the function will serve as the prompt and beginning words to a generated sentence
pipe("I love")

# first we will generate ten statements that will describe a female character and save them to a list

a_woman_is = []

for i in range (0, 10):
  x = pipe('A woman is')
  a_woman_is.append(x)

a_woman_is

# next we will generate ten statements to describe a male character
a_man_is = []

for i in range (0, 10):
  x = pipe('A man is')
  a_man_is.append(x)

a_man_is

a_person_is = []

for i in range (0, 10):
  x = pipe('A person is')
  a_person_is.append(x)

a_person_is

# join outputs for each prompt into one list and save to csv
import pandas as pd

female_bias = []

for i in a_woman_is:
    out = i[0]['generated_text']
    female_bias.append(out)

df = pd.DataFrame({
    'generated text' : female_bias,
})

df.to_csv('at_female_bias.csv')

male_bias = []

for i in a_man_is:
    out = i[0]['generated_text']
    male_bias.append(out)

df = pd.DataFrame({
    'generated text' : male_bias,
})

df.to_csv('at_s1_male_bias.csv')

person_bias = []

for i in a_person_is:
    out = i[0]['generated_text']
    person_bias.append(out)

df = pd.DataFrame({
    'generated text' : person_bias,
})

df.to_csv('at_s1_person_bias.csv')

# prompt the first season transcript model with variance satement starters
# avoiding prompt "Finn says" to avoid an output too simalar to transcript

import pandas as pd
Finn_is = []

for i in range (0, 10):
  x = pipe('Finn is')
  Finn_is.append(x)


at_s1_Finn_is = []

for i in Finn_is:
    out = i[0]['generated_text']
    at_s1_Finn_is.append(out)

df = pd.DataFrame({
    'generated text' : at_s1_Finn_is,
})

df.to_csv('at_s1_Finn_is.csv')

Finn_is_not = []

for i in range (0, 10):
  x = pipe('Finn is not')
  Finn_is_not.append(x)

at_s1_Finn_is_not = []

for i in Finn_is_not:
    out = i[0]['generated_text']
    at_s1_Finn_is_not.append(out)

df = pd.DataFrame({
    'generated text' : at_s1_Finn_is_not,
})

df.to_csv('at_s1_Finn_is_not.csv')

Finn_thinks = []

for i in range (0, 10):
  x = pipe('Finn thinks')
  Finn_thinks.append(x)


at_s1_Finn_thinks = []

for i in Finn_thinks:
    out = i[0]['generated_text']
    at_s1_Finn_thinks.append(out)

df = pd.DataFrame({
    'generated text' : at_s1_Finn_thinks,
})

df.to_csv('at_s1_Finn_thinks.csv')

Finn_does_not_think = []

for i in range (0, 10):
  x = pipe('Finn does not think')
  Finn_does_not_think.append(x)


at_s1_Finn_does_not_think = []

for i in Finn_does_not_think:
    out = i[0]['generated_text']
    at_s1_Finn_does_not_think.append(out)

df = pd.DataFrame({
    'generated text' : at_s1_Finn_does_not_think,
})

df.to_csv('at_s1_Finn_does_not_think.csv')

Finns_emotions_are = []

for i in range (0, 10):
  x = pipe(f"Finn's emotions are") #f string to allow use of apostrophe
  Finns_emotions_are.append(x)

at_s1_Finns_emotions_are = []

for i in Finns_emotions_are:
    out = i[0]['generated_text']
    at_s1_Finns_emotions_are.append(out)

df = pd.DataFrame({
    'generated text' : at_s1_Finns_emotions_are,
})

df.to_csv('at_s1_Finns_emotions_are.csv')

Finns_emotions_are_not = []

for i in range (0, 10):
  x = pipe(f"Finn's emotions are not") #f string to allow use of apostrophe
  Finns_emotions_are_not.append(x)

at_s1_Finns_emotions_are_not = []

for i in Finns_emotions_are_not:
    out = i[0]['generated_text']
    at_s1_Finns_emotions_are_not.append(out)

df = pd.DataFrame({
    'generated text' : at_s1_Finns_emotions_are_not,
})

df.to_csv('at_s1_Finns_emotions_are_not.csv')

at_s10_outputs_all = female_bias + male_bias + person_bias + at_s1_Finn_is + at_s1_Finn_is_not + at_s1_Finn_thinks + at_s1_Finn_does_not_think + at_s1_Finns_emotions_are + at_s1_Finns_emotions_are_not

df = pd.DataFrame({
    'generated text' : at_s1_outputs_all ,
})

df.to_csv('at_s1_outputs_all .csv')